"""50 exercises on Python loops."""

from .base import make_exercise

exercises = [
    # BEGINNER (1-12): for + range, for over a list, basic accumulation
    make_exercise(
        "loop_01",
        "Count with range",
        "loops",
        1,
        "Write a function `count_up(n)` that returns a list of the numbers 0 up to but not including `n`.",
        hints=[
            "range(n) yields 0, 1, ... n-1",
            "Start with an empty list and append inside the loop",
        ],
        solution="def count_up(n):\n    result = []\n    for i in range(n):\n        result.append(i)\n    return result",
        starter_code="def count_up(n):\n    # build a list of 0..n-1\n",
        function_name="count_up",
        test_cases=[((3,), [0, 1, 2]), ((1,), [0]), ((0,), []), ((5,), [0, 1, 2, 3, 4])],
        concepts=["for loop", "range", "append"],
    ),
    make_exercise(
        "loop_02",
        "Sum a list",
        "loops",
        1,
        "Write a function `total(numbers)` that adds up every number in the list using a loop (do not use the built-in sum).",
        hints=[
            "Start a variable at 0 before the loop",
            "Add each item to it with +=",
        ],
        solution="def total(numbers):\n    running = 0\n    for n in numbers:\n        running += n\n    return running",
        starter_code="def total(numbers):\n    running = 0\n",
        function_name="total",
        test_cases=[(([1, 2, 3],), 6), (([],), 0), (([10, -4],), 6), (([5],), 5)],
        concepts=["for loop", "accumulator", "augmented assignment"],
    ),
    make_exercise(
        "loop_03",
        "Count the items",
        "loops",
        1,
        "Write a function `how_many(items)` that counts the items with a loop instead of using len.",
        hints=["Increase a counter by 1 on every pass", "The loop variable itself is not needed"],
        solution="def how_many(items):\n    count = 0\n    for _ in items:\n        count += 1\n    return count",
        starter_code="def how_many(items):\n    count = 0\n",
        function_name="how_many",
        test_cases=[((["a", "b"],), 2), (([],), 0), (([1, 2, 3, 4],), 4)],
        concepts=["for loop", "counter", "throwaway variable"],
    ),
    make_exercise(
        "loop_04",
        "Double every number",
        "loops",
        1,
        "Write a function `double_all(numbers)` that returns a new list with each number multiplied by 2.",
        hints=["Build a fresh list, do not change the original", "append(n * 2) inside the loop"],
        solution="def double_all(numbers):\n    result = []\n    for n in numbers:\n        result.append(n * 2)\n    return result",
        starter_code="def double_all(numbers):\n    result = []\n",
        function_name="double_all",
        test_cases=[(([1, 2, 3],), [2, 4, 6]), (([],), []), (([-1, 0],), [-2, 0])],
        concepts=["for loop", "transform", "append"],
    ),
    make_exercise(
        "loop_05",
        "Range with a start",
        "loops",
        1,
        "Write a function `span(start, stop)` returning a list of the integers from `start` up to but not including `stop`.",
        hints=[
            "range takes two arguments: range(start, stop)",
            "list(range(...)) also works, but write the loop",
        ],
        solution="def span(start, stop):\n    result = []\n    for i in range(start, stop):\n        result.append(i)\n    return result",
        starter_code="def span(start, stop):\n    result = []\n",
        function_name="span",
        test_cases=[((2, 5), [2, 3, 4]), ((0, 1), [0]), ((3, 3), []), ((-2, 1), [-2, -1, 0])],
        concepts=["range", "for loop"],
    ),
    make_exercise(
        "loop_06",
        "Range with a step",
        "loops",
        1,
        "Write a function `evens_below(n)` returning every even number from 0 up to but not including `n`, using range's third argument.",
        hints=["range(0, n, 2) counts in twos", "The third argument is the step"],
        solution="def evens_below(n):\n    result = []\n    for i in range(0, n, 2):\n        result.append(i)\n    return result",
        starter_code="def evens_below(n):\n    result = []\n",
        function_name="evens_below",
        test_cases=[((7,), [0, 2, 4, 6]), ((1,), [0]), ((0,), []), ((10,), [0, 2, 4, 6, 8])],
        concepts=["range step", "for loop"],
    ),
    make_exercise(
        "loop_07",
        "Countdown with a negative step",
        "loops",
        1,
        "Write a function `countdown(n)` returning the numbers from `n` down to 1.",
        hints=["range(n, 0, -1) counts backwards", "The stop value is still excluded"],
        solution="def countdown(n):\n    result = []\n    for i in range(n, 0, -1):\n        result.append(i)\n    return result",
        starter_code="def countdown(n):\n    result = []\n",
        function_name="countdown",
        test_cases=[((3,), [3, 2, 1]), ((1,), [1]), ((0,), []), ((5,), [5, 4, 3, 2, 1])],
        concepts=["range step", "negative step"],
    ),
    make_exercise(
        "loop_08",
        "Loop over a string",
        "loops",
        1,
        "Write a function `letters(word)` returning a list of the characters in `word`, one per item.",
        hints=["A string is iterable: for ch in word", "Append each character"],
        solution="def letters(word):\n    result = []\n    for ch in word:\n        result.append(ch)\n    return result",
        starter_code="def letters(word):\n    result = []\n",
        function_name="letters",
        test_cases=[(("cat",), ["c", "a", "t"]), (("",), []), (("hi",), ["h", "i"])],
        concepts=["iterate string", "for loop"],
    ),
    make_exercise(
        "loop_09",
        "Multiply everything together",
        "loops",
        2,
        "Write a function `product(numbers)` returning the product of all numbers. An empty list gives 1.",
        hints=["Start the accumulator at 1, not 0", "Multiplying by 0 would wipe out the answer"],
        solution="def product(numbers):\n    running = 1\n    for n in numbers:\n        running *= n\n    return running",
        starter_code="def product(numbers):\n    running = 1\n",
        function_name="product",
        test_cases=[(([2, 3, 4],), 24), (([],), 1), (([5],), 5), (([2, 0, 9],), 0)],
        concepts=["accumulator", "identity element"],
    ),
    make_exercise(
        "loop_10",
        "Count matching items",
        "loops",
        2,
        "Write a function `count_positive(numbers)` returning how many numbers are greater than 0.",
        hints=["Combine a for loop with an if", "Only increase the counter when the test passes"],
        solution="def count_positive(numbers):\n    count = 0\n    for n in numbers:\n        if n > 0:\n            count += 1\n    return count",
        starter_code="def count_positive(numbers):\n    count = 0\n",
        function_name="count_positive",
        test_cases=[(([1, -2, 3],), 2), (([],), 0), (([-1, -5],), 0), (([4, 4, 4],), 3)],
        concepts=["for loop", "conditional inside loop", "counter"],
    ),
    make_exercise(
        "loop_11",
        "Keep only the even ones",
        "loops",
        2,
        "Write a function `keep_even(numbers)` returning a new list holding only the even numbers, in the original order.",
        hints=["n % 2 == 0 tests for even", "Append only when the test passes"],
        solution="def keep_even(numbers):\n    result = []\n    for n in numbers:\n        if n % 2 == 0:\n            result.append(n)\n    return result",
        starter_code="def keep_even(numbers):\n    result = []\n",
        function_name="keep_even",
        test_cases=[(([1, 2, 3, 4],), [2, 4]), (([],), []), (([1, 3],), []), (([0, -2],), [0, -2])],
        concepts=["filter pattern", "modulo"],
    ),
    make_exercise(
        "loop_12",
        "Build a sentence",
        "loops",
        2,
        "Write a function `join_words(words)` returning the words joined by a single space, built with a loop (do not use str.join).",
        hints=[
            "Add a space before each word except the first",
            "An empty input returns an empty string",
        ],
        solution="def join_words(words):\n    out = ''\n    for word in words:\n        if out:\n            out += ' '\n        out += word\n    return out",
        starter_code="def join_words(words):\n    out = ''\n",
        function_name="join_words",
        test_cases=[
            ((["a", "b"],), "a b"),
            (([],), ""),
            ((["solo"],), "solo"),
            ((["x", "y", "z"],), "x y z"),
        ],
        concepts=["string accumulation", "first-iteration special case"],
    ),
    # EASY (13-24): while, break, continue, enumerate, zip
    make_exercise(
        "loop_13",
        "A basic while loop",
        "loops",
        2,
        "Write a function `sum_to(n)` returning 1 + 2 + ... + n using a while loop.",
        hints=[
            "Set i = 1 before the loop and increase it inside",
            "Forgetting i += 1 loops forever",
        ],
        solution="def sum_to(n):\n    total = 0\n    i = 1\n    while i <= n:\n        total += i\n        i += 1\n    return total",
        starter_code="def sum_to(n):\n    total = 0\n    i = 1\n",
        function_name="sum_to",
        test_cases=[((5,), 15), ((1,), 1), ((0,), 0), ((10,), 55)],
        concepts=["while loop", "loop counter", "termination"],
    ),
    make_exercise(
        "loop_14",
        "Halve until small",
        "loops",
        2,
        "Write a function `halvings(n)` counting how many times you can halve `n` with integer division before it reaches 0.",
        hints=["Use // for integer division", "Count each pass through the while loop"],
        solution="def halvings(n):\n    steps = 0\n    while n > 0:\n        n = n // 2\n        steps += 1\n    return steps",
        starter_code="def halvings(n):\n    steps = 0\n",
        function_name="halvings",
        test_cases=[((8,), 4), ((1,), 1), ((0,), 0), ((5,), 3)],
        concepts=["while loop", "integer division"],
    ),
    make_exercise(
        "loop_15",
        "Stop early with break",
        "loops",
        2,
        "Write a function `first_negative(numbers)` returning the first negative number, or None if there is none.",
        hints=[
            "return exits the function immediately, no break needed",
            "Return None after the loop if nothing matched",
        ],
        solution="def first_negative(numbers):\n    for n in numbers:\n        if n < 0:\n            return n\n    return None",
        starter_code="def first_negative(numbers):\n",
        function_name="first_negative",
        test_cases=[(([1, -2, -3],), -2), (([1, 2],), None), (([],), None), (([-9],), -9)],
        concepts=["early exit", "return inside loop", "None"],
    ),
    make_exercise(
        "loop_16",
        "Skip with continue",
        "loops",
        2,
        "Write a function `sum_skipping_zeros(numbers)` that adds every number except the zeros, using continue.",
        hints=["continue jumps straight to the next pass", "Test for n == 0 first"],
        solution="def sum_skipping_zeros(numbers):\n    total = 0\n    for n in numbers:\n        if n == 0:\n            continue\n        total += n\n    return total",
        starter_code="def sum_skipping_zeros(numbers):\n    total = 0\n",
        function_name="sum_skipping_zeros",
        test_cases=[(([1, 0, 2],), 3), (([0, 0],), 0), (([],), 0), (([4],), 4)],
        concepts=["continue", "accumulator"],
    ),
    make_exercise(
        "loop_17",
        "Index and value with enumerate",
        "loops",
        2,
        "Write a function `label_items(items)` returning a list of strings like '0:a', '1:b' pairing each index with its value.",
        hints=["for i, value in enumerate(items)", "Build each string with an f-string"],
        solution="def label_items(items):\n    result = []\n    for i, value in enumerate(items):\n        result.append(f'{i}:{value}')\n    return result",
        starter_code="def label_items(items):\n    result = []\n",
        function_name="label_items",
        test_cases=[((["a", "b"],), ["0:a", "1:b"]), (([],), []), ((["x"],), ["0:x"])],
        concepts=["enumerate", "tuple unpacking", "f-string"],
    ),
    make_exercise(
        "loop_18",
        "Find the index",
        "loops",
        2,
        "Write a function `index_of(items, target)` returning the position of the first match, or -1 if absent.",
        hints=["enumerate gives you the index for free", "-1 is the conventional not-found answer"],
        solution="def index_of(items, target):\n    for i, value in enumerate(items):\n        if value == target:\n            return i\n    return -1",
        starter_code="def index_of(items, target):\n",
        function_name="index_of",
        test_cases=[
            ((["a", "b", "c"], "b"), 1),
            ((["a"], "z"), -1),
            (([], "x"), -1),
            (([1, 2, 2], 2), 1),
        ],
        concepts=["enumerate", "search", "sentinel value"],
    ),
    make_exercise(
        "loop_19",
        "Walk two lists with zip",
        "loops",
        2,
        "Write a function `pair_sums(a, b)` returning a list of the element-wise sums. Stop at the shorter list.",
        hints=["zip(a, b) yields pairs and stops at the shorter one", "for x, y in zip(a, b)"],
        solution="def pair_sums(a, b):\n    result = []\n    for x, y in zip(a, b):\n        result.append(x + y)\n    return result",
        starter_code="def pair_sums(a, b):\n    result = []\n",
        function_name="pair_sums",
        test_cases=[(([1, 2], [10, 20]), [11, 22]), (([1, 2, 3], [1]), [2]), (([], []), [])],
        concepts=["zip", "parallel iteration"],
    ),
    make_exercise(
        "loop_20",
        "Largest value by hand",
        "loops",
        2,
        "Write a function `largest(numbers)` returning the biggest number without using max. Return None for an empty list.",
        hints=[
            "Seed the answer with the first element, not 0",
            "Guard the empty case before the loop",
        ],
        solution="def largest(numbers):\n    if not numbers:\n        return None\n    best = numbers[0]\n    for n in numbers:\n        if n > best:\n            best = n\n    return best",
        starter_code="def largest(numbers):\n    if not numbers:\n        return None\n",
        function_name="largest",
        test_cases=[(([3, 9, 2],), 9), (([],), None), (([-5, -2],), -2), (([7],), 7)],
        concepts=["running best", "empty guard"],
    ),
    make_exercise(
        "loop_21",
        "Reverse a list by hand",
        "loops",
        2,
        "Write a function `backwards(items)` returning a new list in reverse order, without using reversed or slicing.",
        hints=["Loop over the indexes from the end downwards", "range(len(items) - 1, -1, -1)"],
        solution="def backwards(items):\n    result = []\n    for i in range(len(items) - 1, -1, -1):\n        result.append(items[i])\n    return result",
        starter_code="def backwards(items):\n    result = []\n",
        function_name="backwards",
        test_cases=[(([1, 2, 3],), [3, 2, 1]), (([],), []), ((["a"],), ["a"])],
        concepts=["index loop", "negative step", "len"],
    ),
    make_exercise(
        "loop_22",
        "Count the vowels",
        "loops",
        2,
        "Write a function `count_vowels(text)` counting the vowels a, e, i, o, u, ignoring case.",
        hints=[
            "Lowercase the character before testing",
            "The in operator tests membership: ch in 'aeiou'",
        ],
        solution="def count_vowels(text):\n    count = 0\n    for ch in text:\n        if ch.lower() in 'aeiou':\n            count += 1\n    return count",
        starter_code="def count_vowels(text):\n    count = 0\n",
        function_name="count_vowels",
        test_cases=[(("hello",), 2), (("",), 0), (("XYZ",), 0), (("AEiou",), 5)],
        concepts=["iterate string", "membership test", "case folding"],
    ),
    make_exercise(
        "loop_23",
        "While with a sentinel",
        "loops",
        3,
        "Write a function `take_until_zero(numbers)` collecting values from the front until a 0 appears. The 0 is not included.",
        hints=["A while loop with an index is one way", "break also works inside a for loop"],
        solution="def take_until_zero(numbers):\n    result = []\n    for n in numbers:\n        if n == 0:\n            break\n        result.append(n)\n    return result",
        starter_code="def take_until_zero(numbers):\n    result = []\n",
        function_name="take_until_zero",
        test_cases=[(([1, 2, 0, 3],), [1, 2]), (([0],), []), (([],), []), (([4, 5],), [4, 5])],
        concepts=["break", "sentinel value"],
    ),
    make_exercise(
        "loop_24",
        "Loop over a dictionary",
        "loops",
        3,
        "Write a function `sum_values(scores)` adding up every value in the dictionary.",
        hints=["scores.values() yields the values", "scores.items() gives key and value pairs"],
        solution="def sum_values(scores):\n    total = 0\n    for value in scores.values():\n        total += value\n    return total",
        starter_code="def sum_values(scores):\n    total = 0\n",
        function_name="sum_values",
        test_cases=[(({"a": 1, "b": 2},), 3), (({},), 0), (({"x": -5},), -5)],
        concepts=["dict iteration", "values()"],
    ),
    # MEDIUM (25-38): nested loops, classic algorithms, accumulation patterns
    make_exercise(
        "loop_25",
        "Multiplication row",
        "loops",
        3,
        "Write a function `times_table(n, upto)` returning the list n*1, n*2, ... n*upto.",
        hints=["range(1, upto + 1) starts at 1 and includes upto", "Off-by-one errors live here"],
        solution="def times_table(n, upto):\n    result = []\n    for i in range(1, upto + 1):\n        result.append(n * i)\n    return result",
        starter_code="def times_table(n, upto):\n    result = []\n",
        function_name="times_table",
        test_cases=[((3, 4), [3, 6, 9, 12]), ((5, 1), [5]), ((2, 0), []), ((-1, 3), [-1, -2, -3])],
        concepts=["range bounds", "off-by-one"],
    ),
    make_exercise(
        "loop_26",
        "Nested loops make pairs",
        "loops",
        3,
        "Write a function `all_pairs(a, b)` returning every (x, y) tuple pairing each item of `a` with each item of `b`.",
        hints=["Put one for loop inside another", "The inner loop restarts on every outer pass"],
        solution="def all_pairs(a, b):\n    result = []\n    for x in a:\n        for y in b:\n            result.append((x, y))\n    return result",
        starter_code="def all_pairs(a, b):\n    result = []\n",
        function_name="all_pairs",
        test_cases=[
            (([1, 2], ["a"]), [(1, "a"), (2, "a")]),
            (([], [1]), []),
            (([1], [2, 3]), [(1, 2), (1, 3)]),
        ],
        concepts=["nested loop", "tuple", "cartesian product"],
    ),
    make_exercise(
        "loop_27",
        "FizzBuzz",
        "loops",
        3,
        "Write a function `fizzbuzz(n)` returning a list for 1..n where multiples of 3 become 'Fizz', of 5 become 'Buzz', of both become 'FizzBuzz', and everything else stays the number.",
        hints=["Test the both-case first, or it never fires", "Numbers stay as ints, not strings"],
        solution="def fizzbuzz(n):\n    result = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            result.append('FizzBuzz')\n        elif i % 3 == 0:\n            result.append('Fizz')\n        elif i % 5 == 0:\n            result.append('Buzz')\n        else:\n            result.append(i)\n    return result",
        starter_code="def fizzbuzz(n):\n    result = []\n",
        function_name="fizzbuzz",
        test_cases=[
            ((5,), [1, 2, "Fizz", 4, "Buzz"]),
            ((3,), [1, 2, "Fizz"]),
            ((0,), []),
            (
                (15,),
                [
                    1,
                    2,
                    "Fizz",
                    4,
                    "Buzz",
                    "Fizz",
                    7,
                    8,
                    "Fizz",
                    "Buzz",
                    11,
                    "Fizz",
                    13,
                    14,
                    "FizzBuzz",
                ],
            ),
        ],
        concepts=["elif ordering", "modulo", "for loop"],
    ),
    make_exercise(
        "loop_28",
        "Factorial",
        "loops",
        3,
        "Write a function `factorial(n)` returning n! using a loop. factorial(0) is 1.",
        hints=[
            "Start at 1 and multiply up to n",
            "range(1, n + 1) is empty when n is 0, which gives the right answer",
        ],
        solution="def factorial(n):\n    result = 1\n    for i in range(1, n + 1):\n        result *= i\n    return result",
        starter_code="def factorial(n):\n    result = 1\n",
        function_name="factorial",
        test_cases=[((5,), 120), ((0,), 1), ((1,), 1), ((6,), 720)],
        concepts=["accumulator", "range bounds"],
    ),
    make_exercise(
        "loop_29",
        "Fibonacci sequence",
        "loops",
        3,
        "Write a function `fib(n)` returning the first `n` Fibonacci numbers starting 0, 1.",
        hints=[
            "Track the previous two values in two variables",
            "a, b = b, a + b updates both at once",
        ],
        solution="def fib(n):\n    result = []\n    a, b = 0, 1\n    for _ in range(n):\n        result.append(a)\n        a, b = b, a + b\n    return result",
        starter_code="def fib(n):\n    result = []\n    a, b = 0, 1\n",
        function_name="fib",
        test_cases=[
            ((5,), [0, 1, 1, 2, 3]),
            ((1,), [0]),
            ((0,), []),
            ((7,), [0, 1, 1, 2, 3, 5, 8]),
        ],
        concepts=["multiple assignment", "state in a loop"],
    ),
    make_exercise(
        "loop_30",
        "Digit sum",
        "loops",
        3,
        "Write a function `digit_sum(n)` adding the decimal digits of a non-negative integer.",
        hints=["n % 10 peels off the last digit", "n //= 10 drops it, and the loop ends at 0"],
        solution="def digit_sum(n):\n    total = 0\n    while n > 0:\n        total += n % 10\n        n //= 10\n    return total",
        starter_code="def digit_sum(n):\n    total = 0\n",
        function_name="digit_sum",
        test_cases=[((123,), 6), ((0,), 0), ((9,), 9), ((1010,), 2)],
        concepts=["while loop", "modulo", "integer division"],
    ),
    make_exercise(
        "loop_31",
        "Reverse a number",
        "loops",
        3,
        "Write a function `reverse_number(n)` turning 123 into 321 using arithmetic, not strings.",
        hints=[
            "Build the answer as reversed = reversed * 10 + digit",
            "Peel digits with % 10 and // 10",
        ],
        solution="def reverse_number(n):\n    out = 0\n    while n > 0:\n        out = out * 10 + n % 10\n        n //= 10\n    return out",
        starter_code="def reverse_number(n):\n    out = 0\n",
        function_name="reverse_number",
        test_cases=[((123,), 321), ((0,), 0), ((100,), 1), ((7,), 7)],
        concepts=["while loop", "digit arithmetic"],
    ),
    make_exercise(
        "loop_32",
        "Prime check",
        "loops",
        3,
        "Write a function `is_prime(n)` returning True when n is prime. Numbers below 2 are not prime.",
        hints=[
            "Test divisors from 2 up to n - 1",
            "Return False the moment a divisor divides evenly",
        ],
        solution="def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, n):\n        if n % d == 0:\n            return False\n    return True",
        starter_code="def is_prime(n):\n    if n < 2:\n        return False\n",
        function_name="is_prime",
        test_cases=[((7,), True), ((1,), False), ((9,), False), ((2,), True), ((0,), False)],
        concepts=["early return", "modulo", "guard clause"],
    ),
    make_exercise(
        "loop_33",
        "Remove duplicates, keep order",
        "loops",
        3,
        "Write a function `dedupe(items)` returning a list with later repeats removed, preserving first-seen order.",
        hints=["Keep a set of what you have already seen", "Membership in a set is the test"],
        solution="def dedupe(items):\n    seen = set()\n    result = []\n    for item in items:\n        if item not in seen:\n            seen.add(item)\n            result.append(item)\n    return result",
        starter_code="def dedupe(items):\n    seen = set()\n    result = []\n",
        function_name="dedupe",
        test_cases=[
            (([1, 2, 1, 3],), [1, 2, 3]),
            (([],), []),
            ((["a", "a"],), ["a"]),
            (([3, 2, 1],), [3, 2, 1]),
        ],
        concepts=["set membership", "order preservation"],
    ),
    make_exercise(
        "loop_34",
        "Count each item",
        "loops",
        3,
        "Write a function `tally(items)` returning a dictionary mapping each item to how many times it appears.",
        hints=[
            "counts.get(item, 0) gives 0 for a first sighting",
            "Assign back into the dictionary",
        ],
        solution="def tally(items):\n    counts = {}\n    for item in items:\n        counts[item] = counts.get(item, 0) + 1\n    return counts",
        starter_code="def tally(items):\n    counts = {}\n",
        function_name="tally",
        test_cases=[((["a", "b", "a"],), {"a": 2, "b": 1}), (([],), {}), (([1, 1, 1],), {1: 3})],
        concepts=["dict accumulation", "get with default"],
    ),
    make_exercise(
        "loop_35",
        "Flatten one level",
        "loops",
        3,
        "Write a function `flatten(rows)` turning a list of lists into a single flat list.",
        hints=["Loop over the rows, then over each row", "extend or an inner append both work"],
        solution="def flatten(rows):\n    result = []\n    for row in rows:\n        for item in row:\n            result.append(item)\n    return result",
        starter_code="def flatten(rows):\n    result = []\n",
        function_name="flatten",
        test_cases=[
            (([[1, 2], [3]],), [1, 2, 3]),
            (([],), []),
            (([[], []],), []),
            (([["a"], ["b", "c"]],), ["a", "b", "c"]),
        ],
        concepts=["nested loop", "flatten"],
    ),
    make_exercise(
        "loop_36",
        "Running totals",
        "loops",
        3,
        "Write a function `running_total(numbers)` returning the cumulative sum after each item.",
        hints=[
            "Keep one accumulator and append it every pass",
            "The output is the same length as the input",
        ],
        solution="def running_total(numbers):\n    result = []\n    total = 0\n    for n in numbers:\n        total += n\n        result.append(total)\n    return result",
        starter_code="def running_total(numbers):\n    result = []\n    total = 0\n",
        function_name="running_total",
        test_cases=[(([1, 2, 3],), [1, 3, 6]), (([],), []), (([5],), [5]), (([1, -1],), [1, 0])],
        concepts=["accumulator", "cumulative sum"],
    ),
    make_exercise(
        "loop_37",
        "Chunk a list",
        "loops",
        4,
        "Write a function `chunk(items, size)` splitting the list into pieces of length `size`. The final piece may be shorter.",
        hints=[
            "Step through the indexes with range(0, len(items), size)",
            "Slice items[i:i + size]",
        ],
        solution="def chunk(items, size):\n    result = []\n    for i in range(0, len(items), size):\n        result.append(items[i:i + size])\n    return result",
        starter_code="def chunk(items, size):\n    result = []\n",
        function_name="chunk",
        test_cases=[
            (([1, 2, 3, 4, 5], 2), [[1, 2], [3, 4], [5]]),
            (([], 3), []),
            (([1, 2], 5), [[1, 2]]),
        ],
        concepts=["range step", "slicing", "index loop"],
    ),
    make_exercise(
        "loop_38",
        "Moving average",
        "loops",
        4,
        "Write a function `moving_average(values, window)` returning the mean of each consecutive window. Return an empty list when the input is shorter than the window.",
        hints=[
            "The last start index is len(values) - window",
            "sum(slice) / window gives each average",
        ],
        solution="def moving_average(values, window):\n    result = []\n    for i in range(len(values) - window + 1):\n        piece = values[i:i + window]\n        result.append(sum(piece) / window)\n    return result",
        starter_code="def moving_average(values, window):\n    result = []\n",
        function_name="moving_average",
        test_cases=[(([1, 2, 3, 4], 2), [1.5, 2.5, 3.5]), (([1], 3), []), (([2, 4, 6], 3), [4.0])],
        concepts=["sliding window", "slicing", "range bounds"],
    ),
    # HARD (39-46): nested logic, two-pointer, sorting, matrix work
    make_exercise(
        "loop_39",
        "Star pyramid",
        "loops",
        4,
        "Write a function `pyramid(n)` returning a list of n strings: one star, then two, and so on.",
        hints=["'*' * i repeats the character", "range(1, n + 1) gives the widths"],
        solution="def pyramid(n):\n    result = []\n    for i in range(1, n + 1):\n        result.append('*' * i)\n    return result",
        starter_code="def pyramid(n):\n    result = []\n",
        function_name="pyramid",
        test_cases=[((3,), ["*", "**", "***"]), ((1,), ["*"]), ((0,), [])],
        concepts=["string repetition", "range bounds"],
    ),
    make_exercise(
        "loop_40",
        "Transpose a grid",
        "loops",
        4,
        "Write a function `transpose(grid)` swapping rows and columns of a rectangular list of lists.",
        hints=[
            "The new row count equals the old column count",
            "Index grid[r][c] inside two loops",
        ],
        solution="def transpose(grid):\n    if not grid:\n        return []\n    result = []\n    for c in range(len(grid[0])):\n        row = []\n        for r in range(len(grid)):\n            row.append(grid[r][c])\n        result.append(row)\n    return result",
        starter_code="def transpose(grid):\n    if not grid:\n        return []\n    result = []\n",
        function_name="transpose",
        test_cases=[
            (([[1, 2], [3, 4]],), [[1, 3], [2, 4]]),
            (([],), []),
            (([[1, 2, 3]],), [[1], [2], [3]]),
        ],
        concepts=["nested index loop", "matrix"],
    ),
    make_exercise(
        "loop_41",
        "Bubble sort",
        "loops",
        4,
        "Write a function `bubble_sort(numbers)` returning a new sorted list using repeated neighbour swaps. Do not call sorted.",
        hints=[
            "Copy the input first with list(numbers)",
            "Swap with items[j], items[j+1] = items[j+1], items[j]",
        ],
        solution="def bubble_sort(numbers):\n    items = list(numbers)\n    for i in range(len(items)):\n        for j in range(len(items) - i - 1):\n            if items[j] > items[j + 1]:\n                items[j], items[j + 1] = items[j + 1], items[j]\n    return items",
        starter_code="def bubble_sort(numbers):\n    items = list(numbers)\n",
        function_name="bubble_sort",
        test_cases=[
            (([3, 1, 2],), [1, 2, 3]),
            (([],), []),
            (([5],), [5]),
            (([2, 2, 1],), [1, 2, 2]),
        ],
        concepts=["nested loop", "swap", "in-place mutation"],
    ),
    make_exercise(
        "loop_42",
        "Binary search",
        "loops",
        4,
        "Write a function `binary_search(sorted_items, target)` returning the index of `target`, or -1. Halve the range each pass.",
        hints=[
            "Track low and high bounds, then compare against the midpoint",
            "mid = (low + high) // 2",
        ],
        solution="def binary_search(sorted_items, target):\n    low = 0\n    high = len(sorted_items) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if sorted_items[mid] == target:\n            return mid\n        if sorted_items[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1",
        starter_code="def binary_search(sorted_items, target):\n    low = 0\n    high = len(sorted_items) - 1\n",
        function_name="binary_search",
        test_cases=[(([1, 3, 5, 7], 5), 2), (([1, 3, 5, 7], 2), -1), (([], 1), -1), (([4], 4), 0)],
        concepts=["while loop", "two bounds", "integer division"],
    ),
    make_exercise(
        "loop_43",
        "Run-length encode",
        "loops",
        4,
        "Write a function `encode(text)` turning 'aaab' into [('a', 3), ('b', 1)].",
        hints=[
            "Track the current character and how many in a row",
            "Flush the last run after the loop ends",
        ],
        solution="def encode(text):\n    result = []\n    current = None\n    count = 0\n    for ch in text:\n        if ch == current:\n            count += 1\n        else:\n            if current is not None:\n                result.append((current, count))\n            current = ch\n            count = 1\n    if current is not None:\n        result.append((current, count))\n    return result",
        starter_code="def encode(text):\n    result = []\n    current = None\n    count = 0\n",
        function_name="encode",
        test_cases=[
            (("aaab",), [("a", 3), ("b", 1)]),
            (("",), []),
            (("ab",), [("a", 1), ("b", 1)]),
            (("cc",), [("c", 2)]),
        ],
        concepts=["state across passes", "flush after loop", "tuple"],
    ),
    make_exercise(
        "loop_44",
        "Two-sum with nested loops",
        "loops",
        4,
        "Write a function `two_sum(numbers, target)` returning the first (i, j) index pair whose values add to `target`, or None.",
        hints=[
            "The inner loop starts at i + 1 to avoid reusing an index",
            "Return as soon as a pair matches",
        ],
        solution="def two_sum(numbers, target):\n    for i in range(len(numbers)):\n        for j in range(i + 1, len(numbers)):\n            if numbers[i] + numbers[j] == target:\n                return (i, j)\n    return None",
        starter_code="def two_sum(numbers, target):\n",
        function_name="two_sum",
        test_cases=[
            (([1, 2, 3], 5), (1, 2)),
            (([1, 2], 9), None),
            (([], 0), None),
            (([3, 3], 6), (0, 1)),
        ],
        concepts=["nested loop", "index pairs", "early return"],
    ),
    make_exercise(
        "loop_45",
        "Collatz steps",
        "loops",
        4,
        "Write a function `collatz_steps(n)` counting how many halve-or-triple steps it takes to reach 1.",
        hints=["Even numbers halve, odd numbers become 3n + 1", "n = 1 needs zero steps"],
        solution="def collatz_steps(n):\n    steps = 0\n    while n != 1:\n        if n % 2 == 0:\n            n //= 2\n        else:\n            n = 3 * n + 1\n        steps += 1\n    return steps",
        starter_code="def collatz_steps(n):\n    steps = 0\n",
        function_name="collatz_steps",
        test_cases=[((1,), 0), ((2,), 1), ((3,), 7), ((6,), 8)],
        concepts=["while loop", "branching inside a loop"],
    ),
    make_exercise(
        "loop_46",
        "Greatest common divisor",
        "loops",
        4,
        "Write a function `gcd(a, b)` using Euclid's method: replace the pair with (b, a % b) until b is 0.",
        hints=["a, b = b, a % b updates both in one line", "The answer is a once b hits 0"],
        solution="def gcd(a, b):\n    while b != 0:\n        a, b = b, a % b\n    return a",
        starter_code="def gcd(a, b):\n",
        function_name="gcd",
        test_cases=[((12, 8), 4), ((7, 13), 1), ((9, 0), 9), ((100, 75), 25)],
        concepts=["while loop", "multiple assignment", "modulo"],
    ),
    # CHALLENGE (47-50): loop-else, generators of state, real-world shapes
    make_exercise(
        "loop_47",
        "The loop else clause",
        "loops",
        5,
        "Write a function `all_positive(numbers)` returning True only when every number is above 0, using a for loop with an else clause.",
        hints=["The else after a for runs only when no break fired", "Break on the first failure"],
        solution="def all_positive(numbers):\n    for n in numbers:\n        if n <= 0:\n            break\n    else:\n        return True\n    return False",
        starter_code="def all_positive(numbers):\n    for n in numbers:\n",
        function_name="all_positive",
        test_cases=[(([1, 2],), True), (([1, -1],), False), (([],), True), (([0],), False)],
        concepts=["for-else", "break", "no-break semantics"],
    ),
    make_exercise(
        "loop_48",
        "Longest winning streak",
        "loops",
        5,
        "Write a function `longest_streak(results)` returning the longest run of consecutive 'W' entries.",
        hints=[
            "Track the current run and the best run separately",
            "Reset the current run on any non-W",
        ],
        solution="def longest_streak(results):\n    best = 0\n    current = 0\n    for r in results:\n        if r == 'W':\n            current += 1\n            if current > best:\n                best = current\n        else:\n            current = 0\n    return best",
        starter_code="def longest_streak(results):\n    best = 0\n    current = 0\n",
        function_name="longest_streak",
        test_cases=[
            (((["W", "W", "L", "W"],)), 2),
            (([],), 0),
            ((["L"],), 0),
            ((["W", "W", "W"],), 3),
        ],
        concepts=["two accumulators", "reset on failure", "streak"],
    ),
    make_exercise(
        "loop_49",
        "Peak drawdown",
        "loops",
        5,
        "Write a function `max_drawdown(equity)` returning the largest drop from any prior peak, as a positive number.",
        hints=["Carry the highest value seen so far", "The drop is peak minus the current value"],
        solution="def max_drawdown(equity):\n    peak = None\n    worst = 0\n    for value in equity:\n        if peak is None or value > peak:\n            peak = value\n        drop = peak - value\n        if drop > worst:\n            worst = drop\n    return worst",
        starter_code="def max_drawdown(equity):\n    peak = None\n    worst = 0\n",
        function_name="max_drawdown",
        test_cases=[
            (([100, 120, 90, 110],), 30),
            (([],), 0),
            (([50],), 0),
            (([10, 5, 20, 1],), 19),
        ],
        concepts=["running peak", "state across passes", "real-world accumulation"],
    ),
    make_exercise(
        "loop_50",
        "Group consecutive runs",
        "loops",
        5,
        "Write a function `group_runs(items)` splitting a list into sublists of equal neighbouring values.",
        hints=[
            "Start a new group whenever the value changes",
            "Append the final group after the loop",
        ],
        solution="def group_runs(items):\n    groups = []\n    current = []\n    for item in items:\n        if current and item != current[-1]:\n            groups.append(current)\n            current = []\n        current.append(item)\n    if current:\n        groups.append(current)\n    return groups",
        starter_code="def group_runs(items):\n    groups = []\n    current = []\n",
        function_name="group_runs",
        test_cases=[
            (([1, 1, 2, 3, 3],), [[1, 1], [2], [3, 3]]),
            (([],), []),
            (([4],), [[4]]),
            ((["a", "b", "b"],), [["a"], ["b", "b"]]),
        ],
        concepts=["grouping", "flush after loop", "look-back with index -1"],
    ),
]
